using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace aiimeta.Formats
{
    /// <summary>Parser for Civitai metadata in ComfyUI flavor.</summary>
    /// <remarks>
    /// Some images generated by Civitai online generator contains
    /// ComfyUI-style Prompt JSON with its own extension in EXIF User Comment.
    /// The prompt data will be handled by <see cref="ComfyParser"/>.
    /// This parser handles the Civitai-specific extension.
    /// </remarks>
    internal class CivitaiComfyParser : IMetadataParser
    {
        public float Priority => 6.5f;

        public void Parse(IMetadata metadata, IParsedMetadata parsed)
        {
            if (string.IsNullOrWhiteSpace(metadata.Parameters)) return;

            // If any preceding parser worked successfully, there is no room for Civitai Comfy.
            if (!string.IsNullOrWhiteSpace(parsed.NegativePromptText) ||
                parsed.Properties.Count() > 1) return;

            var json = JsonHelper.ParseAsJObject(metadata.Parameters);
            if (json is null) return;

            if (json["extraMetadata"]?.AsString()?.ParseAsJObject() is JObject extra_metadata)
            {
                // A1111 parser should have set the raw JSON text in positive prompt text
                // and unset the negative prompt text.
                // So, overwrite the prompt texts if the extraMetadata contains ones.
                if (extra_metadata["prompt"]?.AsString() is string positive)
                {
                    parsed.PositivePromptText = positive;
                }
                if (extra_metadata["negativePrompt"]?.AsString() is string negative)
                {
                    parsed.NegativePromptText = negative;
                }

                // Then, dump the entire extraMetadata into the properties.
                foreach (var property in extra_metadata.Properties())
                {
                    parsed.Add(property.Name, property.Value?.ToString(Formatting.None) ?? string.Empty);
                }
            }

            if (json["extra"]?.ToString(Formatting.None) is string extra)
            {
                parsed.Add("extra", extra);
            }
        }
    }

    public class CivitaiComfyParserFactory : IMetadataParserFactory
    {
        public IMetadataParser GetInstance()
        {
            return new CivitaiComfyParser();
        }
    }
}
